# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'client' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    rn_path = '../node_modules/react-native'
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
    ]
    
    pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
    
    # Pods for client
    
    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

    target 'clientTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end

target 'client-tvOS' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for client-tvOS
    
    target 'client-tvOSTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
